### ISSUE TITLE
[Fix] UserDefaults suitName String 인식불가문제

### ISSUE THREAD

**Issue by yuncoffee** [CoffeeNaeriRei/ScreenTime_Barebones#20]
## 이슈 요약

> AppGroups명을 String 말고 다른 방법으로 넘겨줄 경우 정상적으로 공유되지 않는 문제

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [x] 오류 해결하기

## 참고자료

> 

🔗 [링크](url)

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

1. xcconfig 파일에 값 추가.
![Screenshot 2023-08-13 at 5 10 56 PM](https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/88574289/e66a3928-76a3-4f7c-b2aa-c2239198da6d)

2. info.plist에 값 추가.
![Screenshot 2023-08-13 at 5 11 44 PM](https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/88574289/049e5a1b-6a5a-4092-8358-7f75a941d6a4)

3. Bundle Extension에 사용 코드 추가.
![Screenshot 2023-08-13 at 5 09 42 PM](https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/88574289/0517c26a-84aa-4e1a-abb0-967e37a69ea8)

4. 사용 - 그러나 공유가 제대로 안됨. ㅠ,,
```
// ScheduleVM.swift 

// MARK: - TODO 미친 이슈 발생. String으로 값을 직접 넘겨주지 않을 때 userDefault가 정상동작하지 않음.

// let APP_GROUP_NAME = Bundle.main.appGroupName // Bundle.main에 extension으로 가져옴 -> 앱 제한 안됨

// let APP_GROUP_NAME = Bundle.main.object(forInfoDictionaryKey: "APP_GROUP_NAME") as! String -> 앱 제한 안됨

let APP_GROUP_NAME = "group.coffeenaerirei.screen_time_barebones" // string을 변수에 할당함 -> 앱 제한 됨

class ScheduleVM: ObservableObject {
 @AppStorage("selection", store: UserDefaults(suiteName: APP_GROUP_NAME)) // 여기에 값 전달
    var selection = FamilyActivitySelection()
    ...
}
```
5. 그러나 print로 찍어본 값은 모두 동일함,,
![Screenshot 2023-08-13 at 5 00 54 PM](https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/88574289/96f044f5-3a83-4190-92f4-9793fa5505b2)

위의 값을 모두 print로 조회하였을 경우 동일한 이름이 나옵니다. help,,,

**Comment by kybeen** [comment]
는 너굴맨이 처리했으니 안심하라구
![너굴](https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/89764127/f424358b-f22f-4431-bd42-43deadfaa5c3)
