### ISSUE TITLE
[Fix] 불필요한 ScheduleVM 클래스의 중복 인스턴스 생성 방지

### ISSUE THREAD

**Issue by kybeen** [CoffeeNaeriRei/ScreenTime_Barebones#33]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.
#### ScheduleVM 클래스를 사용하는 곳은 총 3곳입니다.
 - **ScheduleView** 👉 AppStorage 값 + @Published 프로퍼티 사용
 - **MonitoringView** 👉 AppStorage 값만 사용
 - **DeviceActivityMonitorExtension** 👉 AppStorage 값만 사용
 
ScheduleView를 제외하면 AppStorage 값에만 접근하기 때문에 인스턴스를 새로 생성해도 같은 selection 값에 접근하기 때문에 동작에 문제는 없습니다.
## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [x] ScheduleVM 클래스를 @ObservedObject가 아니라 @EnvironmentObject로 사용하도록 코드 수정

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

(PR #31 참고)
<img width="812" alt="image" src="https://github.com/CoffeeNaeriRei/ScreenTime_Barebones/assets/89764127/fc369182-0aac-4ea2-99e1-d7c28ddd8333">

🔗 [링크](url)

## 기타 (스크린샷 등)

> 이슈에 대한 이해를 돕기 위한 자료가 있다면 추가합니다.

싱글톤 패턴 VS @EnvironmentObject 참고 포스팅
- https://onthemud.tistory.com/31

**Comment by yuncoffee** [comment]
DeviceActivityMonitorExtension의 경우 타겟이 달라서 새로 만드는게 하나로 공유가 안될 것 같긴하네요. 나머지는 environmentObject로 처리를 하는게 좋을 것 같아요. 좋은 방법인 것 같습니다 !
