### ISSUE TITLE
ScreenTime always “00:00”

### ISSUE THREAD

**Issue by JunLi0053** [CoffeeNaeriRei/ScreenTime_Barebones#42]
run demo and replace my developer account information in the project， the Report tab can't synchronize the ScreenTime。
Do you need me to set something on my account?

<img width=300 src="https://github.com/user-attachments/assets/fa671beb-a89c-4ffd-adb2-9c8470f42fe4">

**Comment by kybeen** [comment]
Have you selected the app you want to block in the picker?

This view only shows information about the selected apps.
If you want to see all apps, select `All apps & categories` from the picker.

**Comment by JunLi0053** [comment]
> Have you selected the app you want to block in the picker?
> 
> This view only shows information about the selected apps. If you want to see all apps, select `All apps & categories` from the picker.

I already selected the app in the picker, but the ScreenTime has not change

**Comment by kybeen** [comment]
> I already selected the app in the picker, but the ScreenTime has not change

Sorry, I don't know the exact cause either.

I recommend checking again after triggering various screen time monitoring actions.
`ex) tap [save schedules] button`

**Comment by JunLi0053** [comment]
Could you make me the demo Use video ？I want to make sure that ScreenTime is working properly.

**Comment by JunLi0053** [comment]
> > I already selected the app in the picker, but the ScreenTime has not change
> 
> Sorry, I don't know the exact cause either.
> 
> I recommend checking again after triggering various screen time monitoring actions. `ex) tap [save schedules] button`

**Comment by kybeen** [comment]
> Could you make me the demo Use video ？I want to make sure that ScreenTime is working properly.

I'm not sure if this will help, but I hope you find it useful.


https://github.com/user-attachments/assets/c72f65f6-ddbc-4779-ac38-e76368e64415

**Comment by JunLi0053** [comment]
> > Could you make me the demo Use video ？I want to make sure that ScreenTime is working properly.
> 
> I'm not sure if this will help, but I hope you find it useful.
> 
>  screen.mov

**Comment by JunLi0053** [comment]
> > Could you make me the demo Use video ？I want to make sure that ScreenTime is working properly.
> 
> I'm not sure if this will help, but I hope you find it useful.
> 
>  screen.mov

That so weird,I same operation as you,but the time always '00:00' and App list has not things
I print the log at the location of the image below,the 'ss' always '-',This is puzzling
![image](https://github.com/user-attachments/assets/8551493e-a37b-4485-a6a1-83043ae901ec)

**Comment by yuncoffee** [comment]
we need more information. would you check schedule settings feature is working?
Ours Screen Time Project used App Groups. It required Apple Developer Program(paid) Screen Time APi same too.
Your account might need Apple Developer Program active.

- https://developer.apple.com/programs/

**Comment by JunLi0053** [comment]
> we need more information. would you check schedule settings feature is working? Ours Screen Time Project used App Groups. It required Apple Developer Program(paid) Screen Time APi same too. Your account might need Apple Developer Program active.
> 
> * https://developer.apple.com/programs/

My account already active Apple Developer Program and used App Groups，but has same problem。

**Comment by kybeen** [comment]
> That so weird,I same operation as you,but the time always '00:00' and App list has not things I print the log at the location of the image below,the 'ss' always '-',This is puzzling ![image](https://private-user-images.githubusercontent.com/19780832/369215388-8551493e-a37b-4485-a6a1-83043ae901ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjM4OTAsIm5iZiI6MTcyNjgyMzU5MCwicGF0aCI6Ii8xOTc4MDgzMi8zNjkyMTUzODgtODU1MTQ5M2UtYTM3Yi00NDg1LWE2YTEtODMwNDNhZTkwMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzQ5MjllYWFlNTc5NjhkMzRjZTczMzRmYmFlZjg0MjM5YWRmYWU0NzBlMTBkNzI5YTc4MDNkOWJiMDU5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mLTu9ebtM7duMnKv4rBKX3lwnKZRLVket-2yNih7fAs)

But how did you check the value of `ss`?

The values ​​of the extension target cannot be checked in the console.

**Comment by yuncoffee** [comment]
Please check the list below

[ ] Is the APP_GROUP_NAME in App/XCConfig/shared.xcconfig the same as the App Group name in your target's settings?
[ ] Are the Signing Bundle Identifier rules correctly set according to [App, other target] => [com.bundle, com.bundle.targetname]?
[ ] Have you checked your iOS version? (iOS 17.4 has known Bug)
- https://forums.developer.apple.com/forums/thread/750623

My phone and settings are working well, but Screen Time has many bugs 😩, which can vary. Please show me a video of your app in action.

**Comment by JunLi0053** [comment]
> > That so weird,I same operation as you,but the time always '00:00' and App list has not things I print the log at the location of the image below,the 'ss' always '-',This is puzzling ![image](https://private-user-images.githubusercontent.com/19780832/369215388-8551493e-a37b-4485-a6a1-83043ae901ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjM4OTAsIm5iZiI6MTcyNjgyMzU5MCwicGF0aCI6Ii8xOTc4MDgzMi8zNjkyMTUzODgtODU1MTQ5M2UtYTM3Yi00NDg1LWE2YTEtODMwNDNhZTkwMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA5MTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzQ5MjllYWFlNTc5NjhkMzRjZTczMzRmYmFlZjg0MjM5YWRmYWU0NzBlMTBkNzI5YTc4MDNkOWJiMDU5MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mLTu9ebtM7duMnKv4rBKX3lwnKZRLVket-2yNih7fAs)
> 
> But how did you check the value of `ss`?
> 
> The values ​​of the extension target cannot be checked in the console.

I've added Text to the Report page to display 'ss'

**Comment by JunLi0053** [comment]
> Please check the list below
> 
> [ ] Is the APP_GROUP_NAME in App/XCConfig/shared.xcconfig the same as the App Group name in your target's settings? [ ] Are the Signing Bundle Identifier rules correctly set according to [App, other target] => [com.bundle, com.bundle.targetname]? [ ] Have you checked your iOS version? (iOS 17.4 has known Bug)
> 
> * https://forums.developer.apple.com/forums/thread/750623
> 
> My phone and settings are working well, but Screen Time has many bugs 😩, which can vary. Please show me a video of your app in action.

**Comment by kybeen** [comment]
@JunLi0053 
Also, in this project, only the Minimum Deployments version of the ScreenTimeReport target is set differently to 16.0. The version was different from other targets. It may not be related to this issue, but it's worth checking.
> 👉 I just committed the minimum deployments to `iOS 16.2` for all targets.


Additionally, I tested using two iPhone devices, the 17.1.2 iPhone displayed successfully, but the 16.2 iPhone showed nothing in the Report screen.

**Comment by JunLi0053** [comment]
> @JunLi0053 Also, in this project, only the Minimum Deployments version of the ScreenTimeReport target is set differently to 16.0. The version was different from other targets. It may not be related to this issue, but it's worth checking.
> 
> > 👉 I just committed the minimum deployments to `iOS 16.2` for all targets.
> 
> Additionally, I tested using two iPhone devices, the 17.1.2 iPhone displayed successfully, but the 16.2 iPhone showed nothing in the Report screen.

My device is 17.5.1，I downloaded an app called "Cape", and it is normal to use the app's ScreenTime
